### ISSUE TITLE
Changing replicas during rollout can make cluster get stuck rolling out

### ISSUE THREAD

**Issue by ecordell** [authzed/spicedb-operator#108]
If the `SpiceDBCluster` has the condition `WaitingForDeploymentAvailability` and the `spec.config.replicas` value is changed, then the cluster can get stuck in the waiting state:

```yaml
  Conditions:
    Last Transition Time:  2022-11-09T18:38:05Z
    Message:               Waiting for deployment to be available: 3/2 available, 3/2 ready, 3/2 updated, 163/163 generation.
    Reason:                WaitingForDeploymentAvailability
    Status:                True
    Type:                  RollingDeployment
```

As a workaround, this can be fixed by changing the replicas to match the deployment's replicas, waiting for the rollout to finish, and then changing the replicas to the desired value.
