### ISSUE TITLE
memory datastore is set with dispatch enabled by default

### ISSUE THREAD

**Issue by vroldanbet** [authzed/spicedb-operator#111]
Following the example in `README.md` leads to a failure when performing `Check`

```
zed version
client: zed 0.7.5
service: v1.15.0
...
zed permission check blog/post:1 read  blog/user:emilia --revision "${ZEDTOKEN}"
Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.9.11:50053: connect: connection refused"
```

**Comment by vroldanbet** [comment]
The example provided in the `README.md` shows the following custom resource:

```
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: dev
spec:
  config:
    image: ghcr.io/authzed/spicedb:v1.11.0
    datastoreEngine: memory 
  secretName: dev-spicedb-config
```

This results in the following ENVs in the `Deployment`

```
SPICEDB_DATASTORE_ENGINE : memory
SPICEDB_DISPATCH_CLUSTER_ENABLED : false
SPICEDB_DISPATCH_UPSTREAM_ADDR : kubernetes:///dev.default:dispatch
SPICEDB_GRPC_PRESHARED_KEY : secretKeyRef(dev-spicedb-config.preshared_key) 
```

while the cluster dispatch server is disabled, setting `SPICEDB_DISPATCH_UPSTREAM_ADDR` to anything other than an empty string will enable dispatching.

The operator should know memory datastore cannot be dispatched and sett the ENV to empty.

**Comment by vroldanbet** [comment]
Also see https://github.com/authzed/spicedb-operator/issues/30

**Comment by ensonic** [comment]
even using this config:
```yaml
spec:
  config:
    datastoreEngine: memory
    image: authzed/spicedb:v1.15.0
    dispatchUpstreamAddr: ''
```
causes the following env settings on the spicedb deployment
```
SPICEDB_DISPATCH_UPSTREAM_ADDR: kubernetes:///dev.default:dispatch
SPICEDB_DISPATCH_CLUSTER_ENABLED: false
```
