### ISSUE TITLE
Race condition when creating a Spicedb Cluster

### ISSUE THREAD

**Issue by Bhashit** [authzed/spicedb-operator#145]
When creating a new spicedb cluster by following the instructions [here](https://authzed.com/docs/spicedb/operator#create-a-spicedbcluster), the operator can't the find the secret if the both the `SpiceDBCluster` and `Secret` object are created at the same time.

I used the following yamls

```
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: dev
spec:
  config:
    datastoreEngine: postgres
  secretName: dev-spicedb-config
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-spicedb-config
stringData:
  datastore_uri: "postgres://spicedb:<pw>@spicedb-pg.internal:5432/spicedb?sslmode=disable"
  preshared_key: "<some key>"
```

After doing a `kubectl apply -f` with the file containing the above yaml, if I do `kubectl describe spicedbclusters.authzed.com dev`, I get the following output status

```
Name:         dev
Namespace:    bhashit-test
Labels:       <none>
Annotations:  <none>
API Version:  authzed.com/v1alpha1
Kind:         SpiceDBCluster
Metadata:
  Creation Timestamp:  2023-02-10T13:05:13Z
  Generation:          1
  Managed Fields:
    API Version:  authzed.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
    Manager:      spicedb-operator
    Operation:    Apply
    Subresource:  status
    Time:         2023-02-10T13:05:13Z
    API Version:  authzed.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:config:
          .:
          f:datastoreEngine:
          f:extraPodAnnotations:
        f:secretName:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2023-02-10T13:05:13Z
  Resource Version:  1039333060
  UID:               331817c4-46bb-4b12-beef-87a1b5af02d9
Spec:
  Config:
    Datastore Engine:  postgres
    Extra Pod Annotations:
      sidecar.istio.io/inject:  false
  Secret Name:                  dev-spicedb-config
Status:
  Conditions:
    Last Transition Time:  2023-02-10T13:05:13Z
    Message:               Secret bhashit-test/dev-spicedb-config not found
    Reason:                MissingSecret
    Status:                True
    Type:                  PreconditionsFailed
Events:                    <none>
```

The last part is important:

```
Status:
  Conditions:
    Last Transition Time:  2023-02-10T13:05:13Z
    Message:               Secret bhashit-test/dev-spicedb-config not found
    Reason:                MissingSecret
    Status:                True
    Type:                  PreconditionsFailed
```

Ideally, an operator should try a few time with some backoff periods before giving up. That doesn't seem to be happening.

The main problem here is that I can't use an automated deployment tool to deploy spicedb clusters because they remain stuck in the above state. While I can deploy them manually if I deploy the `Secret` first and then deploy the `SpiceDBCluster` instance.
