### ISSUE TITLE
v1.1.2 omits memory datastore from the config file

### ISSUE THREAD

**Issue by sheklesworth** [authzed/spicedb-operator#158]
## Summary
v1.1.2 of the operator does not include the "memory" datastore in the config.yaml included with the image.

## Details
Trying to follow the setup instructions in the [readme](https://github.com/authzed/spicedb-operator/blob/v1.1.2/README.md) after installing the operator generates the following error message after applying the CRD:

```yaml
Status:
  Conditions:
    Last Transition Time:  2023-02-22T23:53:44Z
    Message:               Error validating config with secret hash [redacted]: [couldn't find channel for datastore "memory": no channel found for datastore "memory", no update found in channel]
    Reason:                InvalidConfig
    Status:                True
    Type:                  ValidatingFailed
```

Diving into the operator image at `ghcr.io/authzed/spicedb-operator:v1.1.2` shows this (sorry for the screengrab):

![image](https://user-images.githubusercontent.com/45407631/220796557-7542d56c-be21-47c0-ba52-ec8ea22773b0.png)

In particular, the [default-operator-config.yaml](https://github.com/authzed/spicedb-operator/blob/v1.1.2/default-operator-config.yaml) used as the basis for /opt/operator/config.yaml does not contain the memory datastore. So anyone following along with the readme will fail to create a working SpiceDB Cluster unless they have another supported datastore available.
