### ISSUE TITLE
No default OS affinity but can't run on Windows nodes

### ISSUE THREAD

**Issue by rcmosher** [authzed/spicedb-operator#185]
We're using the spicedb-operator to deploy to our K8S cluster. Our cluster allows for both Linux and Windows nodes. Occasionally we'll end up with a pod trying to start on a Windows node and failing. We can get around this with a patch, but since Windows nodes are not supported it would make sense to exclude it by default.

The patch in our SpiceDBCluster definition is as follows:
```
  patches:
  - kind: '*'
    patch:
      metadata:
        labels:
          added: via-patch
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
```
