### ISSUE TITLE
Feature: additional endpoint configuration for RO

### ISSUE THREAD

**Issue by elebiodaslingshot** [authzed/spicedb-operator#195]
Would like to be able to provide a configuration to spicedb that states an endpoint for writing and an endpoint for reading.

This provides the ability for removing bottlenecks in the network and obtaining HA by scaling out on what is a very read intensive application.

**Comment by vroldanbet** [comment]
@elebiodaslingshot just to clarify, are you referring to different endpoints to separate reads and writes towards the backing datastore? or the SpiceDB API?

**Comment by ecordell** [comment]
(assuming the answer to @vroldanbet's question is that you want separate SpiceDB api endpoints)

You should be able to achieve this with the operator today: spin up two SpiceDB clusters talking to the same datastore, and configure one of them as read-only.

```yaml
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: readwrite
spec:
  config:
    datastoreEngine: postgres
  secretName: spicedb-config
---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: readonly
spec:
  config:
    datastoreEngine: postgres
    datastoreReadonly: "true"
  secretName: spicedb-config
---
apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config
stringData:
  datastore_uri: "postgres://<your backend>"
  preshared_key: "averysecretpresharedkey" 
```

That will result in two clusters, one of which is readonly, and two `Service`s in the cluster that you can route traffic to. 

Is that what you were looking for? Did you try it and run into an issue?
