### ISSUE TITLE
Add default pod topology spread constraints

### ISSUE THREAD

**Issue by jawnsy** [authzed/spicedb-operator#245]
**Summary**

Add a default pod topology spread constraint to prefer scheduling on different nodes, so that failure of a node or zone does not result in an outage of the SpiceDB cluster.

**Background**

When running in a high availability configuration (multiple replicas of SpiceDB), the Kubernetes scheduler may place all the nodes in the same failure domain, such as a particular node or a particular availability zone. In rare instances, this can cause a brief outage:

* If all replicas happen to be in the same node and the node fails, then it may take a moment for Kubernetes to detect that failure and re-schedule pods on other worker nodes in the cluster
* If all replicas happen to be in the same zone and the entire availability zone fails, then it may take some time for Kubernetes to detect the failure

**Workaround**

A solution to this is to add pod topology spread constraints to the resulting pods, with a `whenUnsatisfiable` setting of `ScheduleAnyway` to prevent issues on single-zone clusters. Nodes and availability zones have standard well-known labels for this purpose:

* [`topology.kubernetes.io/zone`](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone)
* [`kubernetes.io/hostname`](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetesiohostname)

The following SpiceDBCluster patches can do this:

```yaml
---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb
spec:
  channel: stable
  config:
    datastoreEngine: postgres
    logLevel: info
    replicas: 3
    serviceAccountName: spicedb
  patches:
    - kind: Deployment
      patch:
        op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                authzed.com/cluster: spicedb
                authzed.com/cluster-component: spicedb
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                authzed.com/cluster: spicedb
                authzed.com/cluster-component: spicedb
  secretName: spicedb
```
