### ISSUE TITLE
Add default resource request/limits for SpiceDB Cluster

### ISSUE THREAD

**Issue by jawnsy** [authzed/spicedb-operator#247]
**Summary**

Add CPU and memory request/limits for SpiceDB Cluster deployment

**Details**

The SpiceDB Deployment manifests are missing resource specs, which means that the resulting pod will have [`BestEffort` quality of service](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#besteffort). This may be non-trivial to set to a reasonable value because resource usage may differ according to user workloads.

For completeness, adding a request would be useful to force the cluster autoscaler to make room for the operator (guaranteeing that some forward progress will be made) and limits would be useful to make issues like leaks more apparent.

**Proposal**

Add a small request and reasonably high limit for the deployment pod spec based on current usage. This will vary based on usage, so having an option in the CRD to override it seems prudent.

As a starting point, something like this seems suitable:

```yaml
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "2000m"
```

**Comment by ecordell** [comment]
This is possible today via the `patches` API:

```yaml
spec:
  patches:
  - kind: Deployment
    patch:
      spec:
        template:
          spec:
            containers:
            - name: spicedb
               resources:
                 requests:
                   memory: "256Mi"
                   cpu: "250m"
                 limits:
                   memory: "1Gi"
                   cpu: "2000m"
```

Although as you note, it's usually better to run SpiceDB in a gauranteed QoS class, and for production clusters we tend to use static cpu allocation as well.

**Comment by n0rthernstar** [comment]
Hello @ecordell could you please clarify if the mentioned example need to be added into the block:

apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb-cluser
  namespace: spicedb
spec:
  **patches:
    - container: spicedb
      patch:
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"**
  config:
    replicas: 1
    datastoreEngine: "postgres"
    telemetryEndpoint: ""
  secretName: spicedb-config

or in another?

**Comment by ecordell** [comment]
Yep, it's in the SpiceDBCluster API.

Full example:
```yaml
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb-cluster
  namespace: spicedb
spec:
  config:
    replicas: 1
    datastoreEngine: "postgres"
    telemetryEndpoint: ""
  secretName: spicedb-config
  patches:
  - kind: Deployment
    patch:
      spec:
        template:
          spec:
            containers:
            - name: spicedb
               resources:
                 requests:
                   memory: "256Mi"
                   cpu: "250m"
                 limits:
                   memory: "1Gi"
                   cpu: "2000m"
```
