### ISSUE TITLE
Specifying environment variables without a prefix

### ISSUE THREAD

**Issue by jzelinskie** [authzed/spicedb-operator#31]
We need to support specifying standard environment variables (e.g. OpenTelemetry).

Right now SpiceDB appends a `SPICEDB_` prefix to everything passed in -- rather those values should be specified in the config and the environment variables should reject anything with the prefix.

**Comment by ecordell** [comment]
This is now possible with the new `patches` field in [v1.2.0](https://github.com/authzed/spicedb-operator/releases/tag/v1.2.0):

something like:
```yaml
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: dev
spec:
  config:
    datastoreEngine: memory
  secretName: dev-spicedb-config
  patches:
  - kind: Deployment
    patch:
      spec:
        template:
          spec:
            containers:
            - name: dev-spicedb
              env:
                 MY_ENV_VAR: "value"
```
