### ISSUE TITLE
SpiceDBCluster definition caused null pointer exception in spiceDB operator

### ISSUE THREAD

**Issue by bradengroom** [authzed/spicedb-operator#357]
Something with this cluster definition generated a deployment that caused a NPE in the operator.

I managed to save this cluster definition:
[spicedbcluster.txt](https://github.com/user-attachments/files/19968910/spicedbcluster.txt)

And these logs:
[spicedb_20operator_20panic.txt](https://github.com/user-attachments/files/19968924/spicedb_20operator_20panic.txt)

Unfortunately, the deployment yaml was lost when we deleted things to restore our operator. I'll follow up with more info if we're able to recover any.

**Comment by tolson-vkn** [comment]
Howdy to provide some more context to what @bradengroom has already.

We're running the [v1.17.0](https://github.com/authzed/spicedb-operator/releases/tag/v1.17.0) bundled distribution with just a pod monitor and _increase_ to the default operator resources...

I can reliably trip over the operator by supplying this YAML. 
```
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb
  namespace: ws-base-default-20250429-f34f19
spec:
  channel: stable
  config:
    datastoreEngine: postgres
  patches:
  - kind: Deployment
    patch:
      metadata:
        creationTimestamp: null
      spec:
        selector: null
        strategy: {}
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
            - env:
              - name: SPICEDB_OTEL_ENDPOINT
                value: nodelocal-ingest.tracing-ingestion-cluster.svc.cluster.local:4317
              - name: SPICEDB_OTEL_INSECURE
                value: 'true'
              - name: SPICEDB_OTEL_PROVIDER
                value: otlpgrpc
              - name: SPICEDB_OTEL_SAMPLE_RATIO
                value: '1.0'
              name: spicedb
              resources:
                requests:
                  cpu: '2'
                  memory: 4Gi
  secretName: spicedb-secret
  version: v1.38.0
---
apiVersion: v1
data:
  # user=postgres password=password host=postgresql port=6543 dbname=spicedb sslmode=disable application_name=spicedb default_query_exec_mode=simple_protocol
  datastore_uri: dXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wYXNzd29yZCBob3N0PXBvc3RncmVzcWwgcG9ydD02NTQzIGRibmFtZT1zcGljZWRiIHNzbG1vZGU9ZGlzYWJsZSBhcHBsaWNhdGlvbl9uYW1lPXNwaWNlZGIgZGVmYXVsdF9xdWVyeV9leGVjX21vZGU9c2ltcGxlX3Byb3RvY29sCg==
  # secret
  preshared_key: c2VjcmV0
kind: Secret
metadata:
  name: spicedb-secret
  namespace: ws-base-default-20250429-f34f19
```

... ancillary equipment is a postgres to connect to configured as above with the same datastore values. 

Launching these two manifests will trigger the `spicedb-migrate-*` process ... this runs successfully (can provide resource yaml)... but it's all appearing nominal:

```
{"level":"info","format":"auto","log_level":"debug","provider":"zerolog","async":false,"time":"2025-04-30T00:30:25Z","message":"configured logging"}
{"level":"info","time":"2025-04-30T00:30:25Z","GOMEMLIMIT":12884901888,"package":"github.com/KimMachineGun/automemlimit/memlimit","time":"2025-04-30T00:30:25Z","message":"GOMEMLIMIT is updated"}
{"level":"debug","time":"2025-04-30T00:30:25Z","message":"maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined"}
{"level":"info","v":0,"provider":"none","endpoint":"","service":"spicedb","insecure":false,"sampleRatio":0.01,"time":"2025-04-30T00:30:25Z","message":"configured opentelemetry tracing"}
{"level":"warn","this-version":"v1.38.0","latest-released-version":"v1.42.1","time":"2025-04-30T00:30:25Z","message":"this version of SpiceDB is out of date. See: https://github.com/authzed/spicedb/releases/tag/v1.42.1"}
{"level":"warn","newCommand":"spicedb datastore migrate","time":"2025-04-30T00:30:25Z","message":"use of deprecated command"}
{"level":"info","time":"2025-04-30T00:30:25Z","message":"migrating postgres datastore"}
{"level":"info","targetRevision":"add-metadata-to-transaction-table","time":"2025-04-30T00:30:25Z","message":"running migrations"}
{"level":"debug","pgx":{"args":[],"commandTag":"SELECT 1","pid":272716621,"sql":"SELECT version_num from alembic_version","time":0.613738},"time":"2025-04-30T00:30:25Z","message":"Query"}
{"level":"info","targetRevision":"add-metadata-to-transaction-table","time":"2025-04-30T00:30:25Z","message":"server already at requested revision"}
```

But after this point the SpiceDB Deployment object is never created and within moments of this completing the SpiceDB Operator will CLBO. In our case this YAML was applied by kubectl client applied which CLBO'ed the spice operator. We scaffold the SpiceDBCluster a bit more in our CI, but the side effect panic is that the whole operator becomes very sad.

All the crash logs provided in the top post but his appears most relevant:
```
goroutine 356 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc006c0c3e0?})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.30.2/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x20d3f80?, 0x3b84500?})
	/opt/hostedtoolcache/go/1.22.8/x64/src/runtime/panic.go:770 +0x132
k8s.io/client-go/applyconfigurations/meta/v1.(*LabelSelectorApplyConfiguration).WithMatchLabels(...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.30.2/applyconfigurations/meta/v1/labelselector.go:39
github.com/authzed/spicedb-operator/pkg/config.(*Config).Deployment(0xc006106000, {0xc001211140, 0x1e}, {0xc0012100e0, 0x1a})
	/home/runner/work/spicedb-operator/spicedb-operator/pkg/config/config.go:812 +0xe9e
github.com/authzed/spicedb-operator/pkg/controller.(*DeploymentHandler).Handle(0xc000ef1b30, {0x27f6ed0, 0xc000e92390})
	/home/runner/work/spicedb-operator/spicedb-operator/pkg/controller/ensure_deployment.go:48 +0x27e
github.com/authzed/spicedb-operator/pkg/controller.NewController.NewHandlerLoggingMiddleware.HandlerLoggingMiddleware.func14.1({0x27f6ed0, 0xc000e92390})
	/home/runner/go/pkg/mod/github.com/authzed/controller-idioms@v0.10.0/middleware/logging.go:36 +0x162
github.com/authzed/controller-idioms/handler.ContextHandlerFunc.Handle(0xc00196e908?, {0x27f6ed0?, 0xc000e92390?})
	/home/runner/go/pkg/mod/github.com/authzed/controller-idioms@v0.10.0/handler/handler.go:31 +0x26
github.com/authzed/spicedb-operator/pkg/controller.(*WaitForMigrationsHandler).Handle(0xc000ef1b90, {0x27f6ed0, 0xc000e92390})
	/home/runner/work/spicedb-operator/spicedb-operator/pkg/controller/wait_for_migrations.go:44 +0x351
github.com/authzed/spicedb-operator/pkg/controller.(*MigrationCheckHandler).Handle(0xc0046cc700, {0x27f6ed0, 0xc000dfe390})
	/home/runner/work/spicedb-operator/spicedb-operator/pkg/controller/check_migrations.go:75 +0x42b
```

~``
pkg/controller/ensure_deployment.go:48 +0x27e
pkg/controller/wait_for_migrations.go:44 +0x351
pkg/controller/check_migrations.go:75 +0x42b
```

Quickly trying to understand what happens here... it looks like we try to create a new deploy config object. Wait for the migrations. That completes successfully. Good deal. From there we try to build out the deployment config but then panic here: https://github.com/authzed/spicedb-operator/blob/main/pkg/config/config.go#L812

To Braden's comment:
> Unfortunately, the deployment yaml was lost when we deleted things to restore our operator. I'll follow up with more info if we're able to recover any.

After looking at and replicating the failure it would seem for this rogue kubectl applied SpiceDBCluster it never actually had a deployment resource, we never got there.

Happy to help provide more context or support.

**Comment by ecordell** [comment]
Can you try removing `selector: null` from the patch you're including on the `SpiceDBCluster`? This looks like the culprit to me. I'll also work on a fix to ensure that this doesn't fail even if you specify that in the patch.

**Comment by ecordell** [comment]
Also, FYI, you should be able to simplify your SpiceDBCluster definition to something like:

```yaml
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb
  namespace: ws-base-default-20250429-f34f19
spec:
  channel: stable
  config:
    datastoreEngine: postgres
    otelEndpoint: nodelocal-ingest.tracing-ingestion-cluster.svc.cluster.local:4317
    otelInsecure: "true"
    otelProvider: otlpgrpc
    otelSampleRatio: "1.0"
  patches:
  - kind: Deployment
    patch:
      spec:
        template:
          spec:
            containers:
              name: spicedb
              resources:
                requests:
                  cpu: '2'
                  memory: 4Gi
  secretName: spicedb-secret
  version: v1.38.0
```
