### ISSUE TITLE
Support setting `--datastore-read-replica-conn-uri` via secret

### ISSUE THREAD

**Issue by bradengroom** [authzed/spicedb-operator#358]
Today, we set the `--datastore-conn-uri` flag by supplying a `datastore_uri` value in the secret with provide to the SpiceDBCluster definition. Exactly as it's done in [this example](https://github.com/authzed/spicedb-operator/blob/08214b70522ddd3904a7357eaefaef99f5eb398f/examples/cockroachdb-tls-ingress/spicedb/spicedb.yaml#L28).

We would like to set the `--datastore-read-replica-conn-uri` flag in a similar way, but this appears to not be supported.

[Discord discussion](https://discord.com/channels/844600078504951838/844600078948630559/1367122617324273736).

**Comment by ecordell** [comment]
Makes sense - in discord you also mentioned that this can be done with a patch, while I'll record here for reference:

```
---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: spicedb-dev-cluster
spec:
  config:
    logLevel: debug
    datastoreEngine: postgres
  secretName: dev-spicedb-secret
  patches:
    - kind: Deployment
      patch:
        spec:
          template:
            spec:
              containers:
                - name: spicedb
                  env:
                    - name: SPICEDB_DATASTORE_READ_REPLICA_CONN_URI
                      valueFrom:
                        secretKeyRef:
                          name: dev-spicedb-secret
                          key: datastore_read_replica_uri
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-spicedb-secret
stringData:
  datastore_uri: postgresql://postgres:password@postgresql:5432/authz
  preshared_key: foo
  datastore_read_replica_uri: postgresql://postgres:password@postgresql:5432/authz
```
