### ISSUE TITLE
[Question] Autoscaling

### ISSUE THREAD

**Issue by AyWa** [authzed/spicedb-operator#88]
Hello,

I had an initial looks at the operator, I wonder if there is any way to have autoscaling like https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ ?

**Comment by ecordell** [comment]
Right now, there's not a great way to use HPA with the operator. The operator enforces a replica count and writes it every time the config changes, so you will see HPA and the operator fight to change the replicas (not continuously, just when there is a config change to the cluster, but it's still not ideal).

We definitely intend to support autoscaling with the operator, though it may or may not involve the HPA autoscaler. Depending on what we do for https://github.com/authzed/spicedb-operator/issues/82 for example, we may be able to scale up by adding nodes and filling their cache before they start responding to traffic.

Right now we tend to run SpiceDB sized for a particular target QPS and scale up as needed. SpiceDB does better with more cores available, so 

Frequent scale up / scale down is probably not ideal for performance since by default we only store 1 copy of a cached item. We could bump the cache spread up, which would require more memory but may make scaling up and down quickly less disruptive (even without cache warming). This could make a lot sense as a way to deploy SpiceDB since it is frequently CPU bound.

@AyWa I'm going to rename this and keep it as a tracking issue for autoscaling support - thanks for kicking off the discussion!

**Comment by tarjanik** [comment]
Hi @ecordell What's the status on this? For us it's likely making sense scaling up and down, even with temporarily reduced performance. To test this, it would be nice to try the workaround, until we have something more sophisticated.

**Comment by ecordell** [comment]
@tarjanik Nothing currently in-flight to support this, but ideas (and PRs!) are welcome. 

The brute-force idea to expose this would be:
- have a flag to disable the operator from setting replicas i.e. `.spec.unmanagedReplicas: true`
- if that flag is set, don't send the replicas in the `apply` api call on the deployment
- this allows you to attach whatever external HPA/VPC/etc to the deployment to control scale

But there might be some better options - I'd need to double check how `HPA` is implemented; if it directly uses the `scale` APIs then this should be possible just by enabling the scale api, with no code changes, and deploying an HPA object and pointing it to the SpiceDBCluster.

**Comment by cucxabong** [comment]
hi there,

do you have any update on this? Thanks

**Comment by AmythD** [comment]
Hello @ecordell, is there any autoscaling option available now? I am using the operator with the community helm chart and can't seem to find a way to set spicedb cluster pod replicas.

Thanks,
Amith

**Comment by project0** [comment]
i would be fine providing my own HPA settings, i mean we already have to provide additional resources anyway such as routing/ingress etc... 
Since this is not going somewhere and there is no real solution .spec.unmanagedReplicas: true might be a good first candidate to move on?

**Comment by ecordell** [comment]
There's some news on this front: #444 merged recently and is in 1.26.1 and up. 

This means you  use the `patches` feature to omit replicas from operator management, leaving you free to manage them with HPA/something else:

```yaml
  patches:
    - kind: Deployment
      patch:
        op: remove
        path: /spec/replicas
```
Prior to #444 this would work but would report a status condition, that PR fixes that so that this becomes a happy path.

Here's a full  LLM-generated example (haven't tested, just wanted to provide a full demonstration of how it fits together):

```yaml
---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: example
  namespace: spicedb
spec:
  config:
    datastoreEngine: cockroachdb
    # The `replicas` value here only sets the Deployment's *initial* replica
    # count. Once the HPA takes over it manages scaling; the operator no longer
    # touches the field. You can omit it entirely.
    replicas: 2
  secretName: example-spicedb-config
  patches:
    # Stop the operator from managing the Deployment's replica count so an
    # external autoscaler can own it. 
    - kind: Deployment
      patch:
        op: remove
        path: /spec/replicas
---
apiVersion: v1
kind: Secret
metadata:
  name: example-spicedb-config
  namespace: spicedb
stringData:
  datastore_uri: "postgresql://root@cockroachdb.cockroachdb:26257/defaultdb?sslmode=disable"
  preshared_key: "averysecretpresharedkey"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-spicedb
  namespace: spicedb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # The operator names the Deployment "<cluster-name>-spicedb".
    name: example-spicedb
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
```

Happy to keep this open though, I think a `.spec. unmanagedReplicas` field makes sense since this should be first-class supported instead of needing to use the patches escape hatch.
